languageCode = "de-DE"
title = "KulturOFFENsive"
baseurl = "http://kultur-offensive.org/"
# baseurl = "https://kulturoffensive.github.io/"
theme = "vienna"
copyright = "&copy; Copyright KulturOFFENsive 2017 - Titelbild: Fotograf & Copyright Jan Vetter"

[params]
    # Social accounts. Link to these accounts are displayed in the header and
    # footer.
    # Google Analytics API key.
    # ga_api_key = "Your Google Analytics tracking id"
    contact = "mailto:mail(at)kultur-offensive.org"

    # Short subtitle/tagline. This is displayed in the header.
    subtitle = "Kreative Projekte und soziales Engagement"
    # themecolor = "#hexcolor" # Defines the tab color in Chrome for Android.
